version: '3.8'

services:
  webapp:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  migration:
    build: .
    container_name: migration_app
    volumes:
      - .:/app
    command: alembic upgrade head
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: